"""Career Driver agent — generates structured career path recommendations."""

METADATA = {
    "id": "career-driver",
    "name": "Career Driver",
    "description": "Discover your next career move — get up to 3 tailored paths with actionable steps, required skills, and salary ranges.",
    "icon": "Briefcase",
    "color": "#10B981",
    "status": "active",
    "outputType": "career_paths",
    "inputFields": [
        {
            "name": "current_role",
            "label": "Current level",
            "type": "select",
            "options": [
                "Not specified",
                "Student / Fresher",
                "Individual Contributor (IC)",
                "Team Lead / Manager",
                "Senior / Staff / Principal",
                "Director / VP",
                "Founder / Freelancer",
            ],
            "default": "Not specified",
            "required": False,
        },
        {
            "name": "experience",
            "label": "Years of experience",
            "type": "select",
            "options": [
                "Not specified",
                "< 1 year",
                "1–3 years",
                "3–5 years",
                "5–10 years",
                "10+ years",
            ],
            "default": "Not specified",
            "required": False,
        },
        {
            "name": "goal",
            "label": "Primary goal",
            "type": "select",
            "options": [
                "Not specified",
                "Higher salary",
                "Move into leadership",
                "More creative / strategic work",
                "Remote / flexible work",
                "Start a business",
                "Better work-life balance",
                "Switch industries",
                "Get into tech",
                "Exit tech",
            ],
            "default": "Not specified",
            "required": False,
        },
        {
            "name": "query",
            "label": "Describe your situation",
            "type": "text",
            "placeholder": "e.g. 4 years in backend dev, bored of execution, want something with more ownership and strategy",
            "required": True,
        },
        {
            "name": "country",
            "label": "Target market",
            "type": "select",
            "options": ["India", "United States", "Europe", "United Kingdom", "Canada", "Australia"],
            "default": "India",
            "required": True,
        },
    ],
    "steps": [
        "Parsing your profile",
        "Researching the job market",
        "Designing career paths",
        "Evaluating feasibility",
        "Building action plans",
    ],
}
